---
title: "Lab 3 Team All Stars"
author: "Johnny Tamanaha, Emily Archambault, Eugene Miller, Kaiyuan Fan, Jingzhi Zhang"
date: "9/13/2019"
output: html_document
---

---

__Question: Does smoking affect health?__

---

__Why is this question important?__

---

__Team Plot:__
```{r}
ggplot(cdc) +
  geom_bar(mapping=aes(x=genhlth, fill=smoke100==1), position="dodge") +
  labs(x="General Health", y="# of People", fill="Did You Smoke 100 Cigarettes?", title="Proportions of Subjects Who've Smoked 100 Cigarettes per Each General Health Category")
```
---

__Conclusion:__

---

__Recommendation for Action:__

---

__Individual Plots__

```{r}
smoke.labs <- c("Nonsmoker", "Smoker")
names(smoke.labs) <- c("0", "1")
ggplot(cdc) +
  geom_freqpoly(mapping=aes(x=age, color=genhlth)) +
  facet_wrap(~smoke100, labeller = labeller(smoke100 = smoke.labs)) +
  labs(x="Age", y="Density", color="General Health", title="General Health Density vs Age Split by Smoker/NonSmoker")
```

Findings: Smokers seem more likely to have poor health at a older age while non-smokers seem to be more likely to have excellent/very good health at a younger age. Density vs Age Split by Smoker/NonSmoker.

